/**************************************************************************
 * Copyright(C),  yuenar2@gmail.com
 * 模块名称:    b9edit
 * 文件名:     SliceEditView.h
 * 模块功能:   切片编辑视图头文件，定义切片编辑视图相关类和接口
 * 创建者:    owenzhang
 * 创建日期:    2026-03-15
 * 版本号:     V1.0.0
 * 历史记录:
 * 1、修改者:   owenzhang
 *    修改日期: 2026-03-15
 *    修改内容: 迁移到Qt6，更新头部注释格式
 ***************************************************************************/
#pragma once

#include <QMainWindow>
// #include "ui_sliceeditview.h"  // Generated by UIC
#include "DrawingContext.h"
#include "b9edit.h"
#include "../crushbitmap.h"
#include <QDialog>
#include <QImage>
#include <QColor>
#include <QTimer>
class B9Edit;

class SliceEditView : public QMainWindow
{
	Q_OBJECT
public:
    SliceEditView(QWidget *parent = 0, Qt::WindowFlags flags = Qt::Window);
	~SliceEditView();

	Ui::B9EditClass ui;
    CrushedPrintJob* pCPJ;//一个指向打印工程文件的指针.
    B9Edit* pBuilder;
	bool modified;
	bool supportMode;	
	int currSlice;
	QString GetEditMode();

    DrawingContext* pDrawingContext; //创建指向绘制控件的指针
public slots:
	void TogSupportMode();
    void GoToSlice(int slicenumber); //开始展示下一个切片的进程..
	void DeCompressIntoContext();
	void ReCompress();
    void RefreshContext(bool alreadywhite);			//刷新
    void UpdateWidgets(); //更新窗口标题，滑块等...
	void RefreshWithGreen();
    //基础类
    void PromptBaseOptions(); //显示基本/填充对话框...
	void PrepareBase(int baselayers, int filledlayers);


    //支撑相关
	void AddSupport(QPoint pos, int size, SupportType type, int fastmode); //creates a new support by startin
	void DeleteAllSupports();

    //撤销
	void ClearUndoBuffer();
	void SaveToUndoBuffer();
	void Undo();
	void Redo();

    //剪贴板（只有在图像模式下可用！）
    void CopyToClipboard();//将当前的图像拷贝到剪贴板。
    void PasteFromClipboard();//从剪贴板取下粘贴，用新的来更换当前切片，也需要做些压缩处理



    //工具
	void SelectPenColor();
    void SelectPenWidth();
	void SetDrawTool(QString tool);
	void SetSupportTool(QString tool);

    //导航栏
	void NextSlice();
	void PrevSlice();
	void PgUpSlice(int increment);
	void PgDownSlice(int increment);
	void BaseSlice();
	void TopSlice();

    //工具栏
    void PopDrawButtons();//取消选中所有绘制按钮
    void SetDrawButtonsEnabled(bool enabled);//设置所有绘制按钮为可用
    void ShowDrawButtons(bool show);//隐藏/显示所有绘制按钮
	
    void PopSupportButtons();//取消选中所有支撑按钮
    void SetSupportButtonsEnabled(bool enabled);//设置所有支撑按钮为可用
    void ShowSupportButtons(bool show);//隐藏/显示所有支撑按钮
	
    //小工具回调
	void on_actionFlood_Fill_activated();
	void on_actionFlood_Void_activated();
	void on_actionWhite_Pen_activated();
	void on_actionBlack_Pen_activated();
	
	void on_actionCircle_activated();
	void on_actionSquare_activated();
	void on_actionTriangle_2_activated();
	void on_actionDiamond_activated();

    // 添加缺失的槽函数
    void updateName(QString s);
    void updateDescription(QString s);
    void updateXY(QString s);
    void updateZ(QString s);
    void ShowSliceWindow();
    void newJob();
    void openJob();
    void saveJob();
    void saveJobAs();
    void importSlices();
    void ExportToFolder();

signals:
    void sliceDirtied(QImage* pNewImg, int slicenumber); //发送信号到父类图像已编辑，并发送指针指向新图像和需要被替换的CrushedBitmap！
    
    // 添加缺失的信号
    void setName(QString s);
    void setDescription(QString s);
    void setXYPixel(QString s);
    void setZLayer(QString s);
    void setSliceIndicator(QString s);

protected:
    void keyPressEvent(QKeyEvent * pEvent);		//处理按键事件
    void keyReleaseEvent(QKeyEvent * pEvent);		// 处理按键释放事件
    void mouseReleaseEvent(QMouseEvent * pEvent);	// 处理鼠标按钮释放事件

	

	
    bool bGrid;				// 如果为真，则绘制网格布局
	int m_xOffset, m_yOffset;
	
private:
	
	QImage topImg;
	QImage botImg;

	QTimer greenTimer;

    QList<QImage> imgBackup;//图像列表，撤消/重做
	int backupIndx;
};

 